# Generated by Django 4.2 on 2024-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='linklists',
            field=models.ManyToManyField(blank=True, null=True, related_name='Links', to='Links.linklist'),
        ),
    ]
