# Generated by Django 4.2 on 2024-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Links', '0002_alter_links_linklists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
