# Generated by Django 4.2 on 2024-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgroup',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
