# Generated by Django 4.2 on 2024-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0002_alter_linkgroup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
