# Generated by Django 4.1.5 on 2024-02-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('is_paid_user', 'Can access paid user features')]},
        ),
    ]
