# Generated by Django 4.1.5 on 2024-02-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_paid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_paid_user',
            new_name='_is_paid_user',
        ),
    ]
