# Generated by Django 4.2 on 2024-03-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_is_paid_user_user__is_paid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useruniquename',
            field=models.CharField(default=' ', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
