# Generated by Django 4.2 on 2024-04-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_useruniquename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useruniquename',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
