# Generated by Django 4.2 on 2024-04-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_useruniquename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useruniquename',
            field=models.CharField(default=' ', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
