# Generated by Django 4.2 on 2024-03-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkAnalytics',
        ),
        migrations.DeleteModel(
            name='LinkGroupAnalytics',
        ),
        migrations.DeleteModel(
            name='UserAnalytics',
        ),
    ]
